name: Daily Property News

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7:00 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 python-dateutil pandas google-api-python-client google-auth-httplib2 google-auth-oauthlib
          
      - name: Create directories
        run: |
          mkdir -p exports
          mkdir -p images
          mkdir -p articles
          
      - name: Run property news scripts
        env:
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: |
          python fetch_news.py
          python create_social_content.py
          python create_final_csv.py
          python unsplash_image_finder.py
          
      - name: Debug CSV file
        run: |
          echo "Checking CSV file content:"
          ls -la exports/
          head -n 5 exports/property_news_social_content_with_images_*.csv
          
      - name: Create credentials file directly
        run: |
          cat > credentials.json << 'EOL'
          ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          EOL
          # Check file was created
          ls -la credentials.json
          head -c 50 credentials.json
          
      - name: Upload to Google Sheets
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: |
          python upload_to_sheets.py
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: property-news-files
          path: |
            exports/*.csv
            exports/upload_complete.txt
            images/*.jpg
            
      - name: Notify on completion
        if: success() 
        run: |
          echo "Property news automation completed successfully!"
          echo "CSV files and images are available as artifacts."
          
      - name: Notify on failure
        if: failure()
        run: |
          echo "Property news automation failed. Check the logs for details."
