name: Daily Property News

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7:00 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 python-dateutil
          
      - name: Run property news scripts
        env:
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: |
          mkdir -p exports
          mkdir -p images
          python fetch_news.py
          python create_social_content.py
          python create_final_csv.py
          python unsplash_image_finder.py
          
      - name: Upload CSV files
        uses: actions/upload-artifact@v4
        with:
          name: property-news-csv
          path: exports/*.csv
          
      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: property-news-images
          path: images/*.jpg
