name: Daily Property News

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7:00 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 python-dateutil unsplash-python
          
      - name: Run property news scripts
        env:
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: |
          python fetch_news.py
          python create_social_content.py
          python create_final_csv.py
          python updated_unsplash_image_finder.py
          
      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v3
        with:
          name: property-news-csv
          path: exports/property_news_social_content_with_images_*.csv
          
      - name: Upload images as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: property-news-images
          path: images/*.jpg
