name: Daily Property News

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7:00 AM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is important for pushing to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4 python-dateutil pandas google-api-python-client google-auth-httplib2 google-auth-oauthlib pillow
          
      - name: Create directories
        run: |
          mkdir -p exports
          mkdir -p images
          mkdir -p articles
          mkdir -p formatted
          
      - name: Run daily property news scripts
        env:
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python fetch_news_daily.py
          python content_tracking_system.py
          python ai_content_generator.py
          python create_social_content_daily.py
          python create_final_csv_daily.py
          
      - name: Debug files
        run: |
          echo "Checking CSV files:"
          ls -la exports/
          echo "Checking CSV content:"
          head -n 5 exports/*.csv
          
      - name: Create credentials file directly
        run: |
          cat > credentials.json << 'EOL'
          ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          EOL
          # Check file was created
          ls -la credentials.json
          
      - name: Relevant Image Solution - Content-based matching
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: |
          python relevant_image_solution.py
          
      - name: Commit images to repository
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add images/
          git commit -m "Add property news images [skip ci]" || echo "No changes to commit"
          git push || echo "Nothing to push"
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: property-news-files
          path: |
            exports/*.csv
            exports/upload_complete.txt
            images/*.jpg
            
      - name: Notify on completion
        if: success()
        run: |
          echo "Daily property news automation completed successfully!"
          echo "CSV files with 2 posts per platform per day and relevant images are available as artifacts."
          
      - name: Notify on failure
        if: failure()
        run: |
          echo "Daily property news automation failed. Check the logs for details."
